# Generated by Django 3.1.6 on 2021-06-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_url',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest_url',
            new_name='twitter_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tweeter_url',
            new_name='youtube_url',
        ),
    ]
