version: '3.7'

services:
  web:
   build: .
    # command: python /portfolio_blog/manage.py runserver 0.0.0.0:8000
   command: gunicorn portfolio_blog_pro.wsgi -b 0.0.0.0:8000
   environment:
    - ENVIRONMENT=production
    - SECRET_KEY=i!3#zqe%cl_qzl$$fv_u!6r-*guo17)ngx_+8_1tttou_ya!dpg
    - DEBUG=0
   volumes:
     - .:/portfolio_blog
   ports:
     - 8000:8000
   depends_on:
     - db
  
  db:
   image: postgres:11
   restart: always
   environment: 
      - POSTGRES_DB=portfolio_blog_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bismillah_19@pg
   volumes:
    - pg_data:/var/lib/postgresql/data/
  
volumes:
  pg_data: