version: '3.7'

services:
  web:
   build: .
   command: python /portfolio_blog/manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/portfolio_blog
   ports:
     - 8000:8000
   depends_on:
     - db
  
  db:
   image: postgres:11
   environment: 
      - POSTGRES_DB=portfolio_blog_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bismillah_19@pg
   volumes:
    - pg_data:/var/lib/postgresql/data/
  
volumes:
  pg_data: